### ISSUE TITLE
 AppImageLauncher no longer builds on Arch Linux

### ISSUE THREAD

**Issue by FabioLolix** [TheAssassin/AppImageLauncher#574]
### Pre-submit checks

- [X] I [checked for similar issues](https://github.com/TheAssassin/AppImageLauncher/issues?q=) beforehand, but could not find any, not even closed ones. I could not add my bug report to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Describe the bug

Hello, [AUR appimagelauncher-git pkgbuild](https://aur.archlinux.org/packages/appimagelauncher-git) maintainer here, the program no longer build from the latest commit
This is using system's libappimage at v1.0.4.5, I've started to work on a pkgbuild that bundle libappimage but it have other issues

btw the `cpr` fork as submodule used is 4+ years and 902 commits behind upstream https://github.com/AppImageCommunity/cpr

```
[ 34%] Automatic MOC and UIC for target translationmanager
patching ELF file 'libbinfmt-bypass-preload.so'
clearing symbol version for dlsym
writing libbinfmt-bypass-preload.so
patching ELF file 'libbinfmt-bypass-preload_32bit.so'
clearing symbol version for dlsym
writing libbinfmt-bypass-preload_32bit.so
[ 34%] Built target translationmanager_autogen
Error: found symbol version markers newer than 2.4:
                 w _ITM_deregisterTMCloneTable
                 w _ITM_registerTMCloneTable
                 w __cxa_finalize@GLIBC_2.2.5
                 U __errno_location@GLIBC_2.2.5
                 w __gmon_start__
                 U __stack_chk_fail@GLIBC_2.4
                 U __vfprintf_chk@GLIBC_2.3.4
                 U calloc@GLIBC_2.2.5
                 U dlsym
                 U exit@GLIBC_2.2.5
                 U free@GLIBC_2.2.5
                 U getenv@GLIBC_2.2.5
                 U malloc@GLIBC_2.2.5
                 U memcpy@GLIBC_2.14
                 U stderr@GLIBC_2.2.5
                 U strdup@GLIBC_2.2.5
                 U strerror@GLIBC_2.2.5
                 U strlen@GLIBC_2.2.5
                 U strncmp@GLIBC_2.2.5
                 U strncpy@GLIBC_2.2.5
                 U unsetenv@GLIBC_2.2.5
make[2]: *** [src/binfmt-bypass/CMakeFiles/binfmt-bypass-preload.dir/build.make:114: src/binfmt-bypass/libbinfmt-bypass-preload.so] Error 1
make[2]: *** Deleting file 'src/binfmt-bypass/libbinfmt-bypass-preload.so'
make[1]: *** [CMakeFiles/Makefile2:1850: src/binfmt-bypass/CMakeFiles/binfmt-bypass-preload.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 36%] Linking C static library libzsync.a
[ 36%] Built target binfmt-bypass-preload_32bit
[ 37%] Linking CXX static library hashlib.a

```
and

```
[ 37%] Linking CXX static library ../../../../../../libcpr.a
[ 37%] Built target cpr
make: *** [Makefile:156: all] Error 2
==> ERROR: A failure occurred in build().
```

build() function log [appimagelauncher-git-r1251.71e8e32-1-x86_64-build.log](https://github.com/TheAssassin/AppImageLauncher/files/11715920/appimagelauncher-git-r1251.71e8e32-1-x86_64-build.log)

### Expected behavior

Package build fine

### Steps to reproduce the issue

sudo pacman -S --needed git base-devel
git clone https://aur.archlinux.org/appimagelauncher-git.git
cd appimagelauncher-git
makepkg -s

### Distribution and desktop environment

Arch Linux
Cinnamon 5.8.1
Kernel 6.1.33
GCC 13.1.1
Glibc 2.37
Qt5  5.15.9+kde+r155

### Installed AppImageLauncher version

N/A

**Comment by TheAssassin** [comment]
Feel free to use upstream CPR.

**Comment by TheGamerCanine** [comment]
I should mention that this problem went away by downloading appimagelauncher by itself from the AUR instead of the appimagelauncher-git package, seems to fix the problem entirely.

**Comment by lvisb** [comment]
+1

**Comment by FabioLolix** [comment]
> I should mention that this problem went away by downloading appimagelauncher by itself from the AUR instead of the appimagelauncher-git package, seems to fix the problem entirely.

@TheGamerCanine that is an older version, I try VCS build to catch this kind of problems before the next release come out

***

> Feel free to use upstream CPR.

[Trying v1.10.5 ](https://github.com/FabioLolix/PKGBUILD-AUR_fix/commit/dbafba05123a2bd68d03ec33ba98b9f4224412df) fail with 

```
-- CXX standard of parent project: 11
CMake Error at lib/AppImageUpdate/lib/zsync2/lib/cpr/CMakeLists.txt:27 (message):
  cpr 1.10.5 does not support 11.  Please use cpr <= 1.9.x

-- Configuring incomplete, errors occurred!
==> ERROR: A failure occurred in build().
```

[Trying v1.9.7](https://github.com/FabioLolix/PKGBUILD-AUR_fix/commit/d66dba55cf2f1f6231eb965f5608f91b42ffcd01) fail with 

```
-- Configuring done (30.9s)
CMake Error: The inter-target dependency graph contains the following strongly connected component (cycle):
  "translationmanager" of type SHARED_LIBRARY
    depends on "shared" (weak)
    depends on "trashbin" (weak)
    depends on "translationmanager_autogen" (strong)
  "translationmanager_autogen" of type UTILITY
    depends on "shared" (strong)
  "trashbin" of type STATIC_LIBRARY
    depends on "shared" (weak)
    depends on "translationmanager" (weak)
  "shared" of type STATIC_LIBRARY
    depends on "translationmanager" (weak)
    depends on "trashbin" (weak)
    depends on "shared_autogen" (strong)
  "shared_autogen" of type UTILITY
    depends on "translationmanager" (strong)
At least one of these targets is not a STATIC_LIBRARY.  Cyclic dependencies are allowed only among static libraries.
CMake Generate step failed.  Build files cannot be regenerated correctly.
==> ERROR: A failure occurred in build().
```

**Comment by ThatOneCalculator** [comment]
Interestingly, I was able to get it to work with the `appimagelauncher` AUR package  v2.2.0-6

**Comment by 4amMusic** [comment]
> Interestingly, I was able to get it to work with the `appimagelauncher` AUR package v2.2.0-6

Thanks. That version worked

**Comment by vivekpal1** [comment]
I was also getting same issue
also tried changing versions

```
:: Processing package changes...
(1/4) removing squashfuse                                  [################################] 100%
(2/4) removing cmake                                       [################################] 100%
(3/4) removing rhash                                       [################################] 100%
(4/4) removing cppdap                                      [################################] 100%
:: Running post-transaction hooks...
(1/4) Arming ConditionNeedsUpdate...
(2/4) Updating the MIME type database...
(3/4) Updating icon theme caches...
(4/4) Updating the desktop file MIME type cache...
 -> Failed to install the following packages. Manual intervention is required:
appimage-git - exit status 4

```

**Comment by trinitronx** [comment]
Cross-posting here for visibility to those affected who are not checking the [AUR package comments][3]:

I managed to [make a patch, add a few `makedepends`, and disable some compiler warnings][1] to workaround the [FTBFS][2] issues with current `appimagelauncher-git` AUR package + submodules.  Pushed the [`PKGBUILD` changes up on my fork here][1].

**Note** that it's not intended that this bandaid-patch workaround be used in any production-grade capacity, but if anyone needs to get latest sources for `appimagelauncher` to build for some reason, maybe this helps?

[1]: https://gitlab.archlinux.org/trinitronx/appimagelauncher-git/-/merge_requests/1/diffs
[2]: https://wiki.debian.org/FTBFS
[3]: https://aur.archlinux.org/packages/appimagelauncher-git#comment-990840

**Comment by FabioLolix** [comment]
Hi @trinitronx you're welcome to make a PR here https://github.com/FabioLolix/PKGBUILD-AUR_fix/tree/master/a/appimagelauncher-git for the pkgbuild

**Comment by trinitronx** [comment]
Thanks!  I've pushed up FabioLolix/PKGBUILD-AUR_fix#45 for the `zsync2-git` package build errors.

It looks like most of the changes including `makedepends` and `CFLAGS` were already applied to [this version][1].  However, now I'm able to reproduce the error mentioned above. :thinking: 

<details><summary>Expand for error details</summary>
<p>

```console
patching ELF file 'libbinfmt-bypass-preload.so'
clearing symbol version for dlsym
writing libbinfmt-bypass-preload.so
[ 23%] Building C object lib/AppImageUpdate/lib/zsync2/lib/zlib/CMakeFiles/zsync2_libz.dir/trees.c.o
[ 23%] Linking CXX shared library libbinfmt-bypass-preload_32bit.so
[ 24%] Building CXX object lib/AppImageUpdate/lib/zsync2/lib/cpr/cpr/CMakeFiles/cpr.dir/payload.cpp.o
[ 24%] Building C object lib/AppImageUpdate/lib/zsync2/lib/zlib/CMakeFiles/zsync2_libz.dir/gzio.c.o
Error: found symbol version markers newer than 2.4:
                 U calloc@GLIBC_2.2.5
                 w __cxa_finalize@GLIBC_2.2.5
                 U dlsym
                 U __errno_location@GLIBC_2.2.5
                 U exit@GLIBC_2.2.5
                 U free@GLIBC_2.2.5
                 U getenv@GLIBC_2.2.5
                 w __gmon_start__
                 w _ITM_deregisterTMCloneTable
                 w _ITM_registerTMCloneTable
                 U malloc@GLIBC_2.2.5
                 U memcpy@GLIBC_2.14
                 U __stack_chk_fail@GLIBC_2.4
                 U stderr@GLIBC_2.2.5
                 U strdup@GLIBC_2.2.5
                 U strerror@GLIBC_2.2.5
                 U strlen@GLIBC_2.2.5
                 U strncmp@GLIBC_2.2.5
                 U strncpy@GLIBC_2.2.5
                 U unsetenv@GLIBC_2.2.5
                 U vfprintf@GLIBC_2.2.5
make[2]: *** [src/binfmt-bypass/CMakeFiles/binfmt-bypass-preload.dir/build.make:121: src/binfmt-bypass/libbinfmt-bypass-preload.so] Error 1
make[2]: *** Deleting file 'src/binfmt-bypass/libbinfmt-bypass-preload.so'
make[1]: *** [CMakeFiles/Makefile2:2194: src/binfmt-bypass/CMakeFiles/binfmt-bypass-preload.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

</p>
</details>

I notice that the current [`PKGBUILD` @ 4cb4a04][2] up on the AUR has some slight differences to this version in the `PKGBUILD-AUR_fix` repo.  It includes the changes [here][3], as well as some of those I needed to fix based on the AUR one, plus extra `CFLAGS` and new dependency on `appimageupdate-git` also.  That pulls in the `zsync2-git` and some other library packages.  I had to patch the `zsync2-git` `PKGBUILD` with `CFLAGS` to ignore the compiler errors (FabioLolix/PKGBUILD-AUR_fix#45).  Then, I tried to rebuild after getting dependencies installed and was able to reproduce the error mentioned above.  Here's the diff between those two `PKGBUILD`s, taken from a point on `master` for both repos without my changes applied:

<details><summary>Expand for diff</summary>
<p>

`$ diff -Naur ~/src/pub/pkgbuild/appimagelauncherd-fixes/appimagelauncher-git/PKGBUILD  ~/src/pub/pkgbuild/appimagelauncherd-fixes/PKGBUILD-AUR_fix/a/appimagelauncher-git/PKGBUILD`:

```diff
--- /home/exampleusr/src/pub/pkgbuild/appimagelauncherd-fixes/appimagelauncher-git/PKGBUILD	2024-09-15 05:59:37.585801810 -0600
+++ /home/exampleusr/src/pub/pkgbuild/appimagelauncherd-fixes/PKGBUILD-AUR_fix/a/appimagelauncher-git/PKGBUILD	2024-09-15 06:00:58.854605927 -0600
@@ -3,21 +3,21 @@
 # Contributor: TheAssassin
 
 pkgname=appimagelauncher-git
-pkgver=r1251.71e8e32
+pkgver=r1257.0013516
 pkgrel=1
 pkgdesc="A Helper application for running and integrating AppImages."
 arch=(x86_64)
 url="https://assassinate-you.net/tags/appimagelauncher/"
 license=(MIT)
 depends=(qt5-base fuse2 squashfuse libappimage libxpm)
-makedepends=(git cmake boost qt5-tools qt5-declarative lib32-glibc lib32-gcc-libs xxd chrpath)
+makedepends=(git cmake boost qt5-tools qt5-declarative lib32-glibc lib32-gcc-libs xxd chrpath patchelf appimageupdate-git)
 provides=(appimagelauncher)
 conflicts=(appimagelauncher)
 source=("git+https://github.com/TheAssassin/AppImageLauncher.git"
         "git+https://github.com/AppImageCommunity/AppImageUpdate.git"
-        #"git+https://github.com/AppImageCommunity/libappimage.git"
-        "git+https://github.com/TheAssassin/zsync2.git"
-        "git+https://github.com/TheAssassin/fltk-1.3.4.git"
+        #"git+https://github.com/AppImage/libappimage.git"
+        "git+https://github.com/AppImageCommunity/zsync2.git"
+        "git+https://github.com/AppImageCommunity/fltk-1.3.4.git"
         "git+https://github.com/TheAssassin/libdesktopenvironments.git"
         "git+https://github.com/arsenm/sanitizers-cmake.git"
         "git+https://github.com/google/googletest.git"
@@ -41,6 +41,8 @@
   #git describe --long --tags --exclude continuous | sed 's/^v//;s/\([^-]*-g\)/r\1/;s/-/./g'
 }
 
+CFLAGS="$CFLAGS -Wno-deprecated-declarations -Wno-discarded-qualifiers -Wno-implicit-function-declaration -Wno-incompatible-pointer-types"
+
 prepare() {
   cd AppImageLauncher
 
@@ -74,12 +76,16 @@
 build() {
   cd AppImageLauncher
 
-  cmake . -Wno-dev \
+  cmake . \
+    -Wno-dev \
         -DCMAKE_INSTALL_PREFIX=/usr/ \
         -DUSE_SYSTEM_LIBAPPIMAGE=ON \
         -DBUILD_TESTING=OFF
+
   make libappimageupdate libappimageupdate-qt
+
   cmake .
+
   make
 }
 
@@ -95,3 +101,7 @@
   #chrpath --delete "${pkgdir}/usr/bin/ail-cli"
   #chrpath --delete "${pkgdir}/usr/bin/appimagelauncherd"
 }
+
+# USE_SYSTEM_GTEST=ON don't have effect on zsync2 submodule
+
+# problems with system's libappimageupdate (not recognized)

```

</p>
</details>

For some reason, I'm able to build the AUR version with my changes on top, but not this one. :shrug: 

[1]: https://github.com/FabioLolix/PKGBUILD-AUR_fix/blob/master/a/appimagelauncher-git/PKGBUILD#L13
[2]: 
[3]: https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=appimagelauncher-git&id=4cb4a04f7cd16d11c5c470d606ac022f8c2357cc

**Comment by FabioLolix** [comment]
> I notice that the current [PKGBUILD @ 4cb4a04][2] up on the AUR has some slight differences to this version in the PKGBUILD-AUR_fix repo

AUR pkgbuild was slightly outdated because I develop the pkgbuilds on github and then sync them, make some tests there etc.., and IMO there isn't much hurry to push changes if the program is broken

Cleaned up some things, so the program build fine with devtools (See https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot#Convenience_way)

Still have the error reported in the first post when building with `makepkg` don't know what is causing that

**Comment by trinitronx** [comment]
> AUR pkgbuild was slightly outdated because I develop the pkgbuilds on github and then sync them, make some tests there etc.., and IMO there isn't much hurry to push changes if the program is broken

Makes sense :+1:, it seems that even old builds of this package (at least on Arch-based distros) has been broken for at least 2 years and is causing a lot of coredumps + disk space usage buildup due to [SystemD restarting it][3].

> Still have the error reported in the first post when building with `makepkg` don't know what is causing that

I think that I just found what the source of the error is.  It's due to the changes in c810e707, which seems to be to "improve compatibility" for old CentOS 7 docker containers.

Specifically, it's from [lines 31-33][1] which output the message: `Error: found symbol version markers newer than 2.4` (set by [`glibc_ok_version`][2]), and exit with error status: `exit 1`.  That causes the build to fail after that step.

I just tested commenting out some lines in `CMakeLists.txt` that runs that script:

<details><summary>Expand for diff</summary>
<p>

```diff
diff --git a/src/binfmt-bypass/CMakeLists.txt b/src/binfmt-bypass/CMakeLists.txt
index 87773fd..e443863 100644
--- a/src/binfmt-bypass/CMakeLists.txt
+++ b/src/binfmt-bypass/CMakeLists.txt
@@ -58,13 +58,13 @@ function(make_preload_lib_target target_name)
     )
 
     # a bit of a hack, but it seems to make binfmt bypass work in really old Docker images (e.g., CentOS <= 7)
-    add_custom_command(
-        TARGET ${target_name}
-        POST_BUILD
-        COMMAND bash ${CMAKE_CURRENT_SOURCE_DIR}/fix-preload-library.sh $<TARGET_FILE_NAME:${target_name}>
-        WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
-        VERBATIM
-    )
+#    add_custom_command(
+#        TARGET ${target_name}
+#        POST_BUILD
+#        COMMAND bash ${CMAKE_CURRENT_SOURCE_DIR}/fix-preload-library.sh $<TARGET_FILE_NAME:${target_name}>
+#        WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
+#        VERBATIM
+#    )
 endfunction()
 
 make_preload_lib_target(${preload_lib})

```

</p>
</details>

Then, the `makepkg` succeeded!  So, we have a way to fix or work around it now... but maybe at the expense of whatever the issue was with CentOS 7 ([now discontinued & EoL][4], thanks to [RedHat's recent decisions][5]).

I'm not sure how comfortable I am with using `elfpatch` during a build, especially with hardcoded version numbers involved... seems fragile. 🤔
There is also this comment... :shrug:

    # a bit of a hack, but it seems to make binfmt bypass work in really old Docker 

Maybe @TheAssassin knows more about the context and rationale for doing this? :shrug:

[1]: https://github.com/TheAssassin/AppImageLauncher/blob/c810e7070e70e735edbd4be3e8e932e4e3f1a666/src/binfmt-bypass/fix-preload-library.sh#L31-L33
[2]: https://github.com/TheAssassin/AppImageLauncher/blob/c810e7070e70e735edbd4be3e8e932e4e3f1a666/src/binfmt-bypass/fix-preload-library.sh#L5
[3]: https://www.reddit.com/r/archlinux/comments/uyjz03/appimagelauncher_process_error_logs_are_clogging/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
[4]: https://www.redhat.com/en/topics/linux/centos-linux-eol
[5]: https://www.theregister.com/2023/06/23/red_hat_centos_move/

**Comment by trinitronx** [comment]
@FabioLolix: Until we hear back, I've prepped a PR #662 which reverts those changes and fixes the FTBFS issue.  If this merges, we may be able to drop `patchelf` from the `makedepends` too.

**Comment by FabioLolix** [comment]
Build again https://aur.archlinux.org/cgit/aur.git/commit/?h=appimagelauncher-git&id=5c8844eeb18f1a4d86bf18270ee7546aec804bf6

**Comment by trinitronx** [comment]
@FabioLolix:

> Build again https://aur.archlinux.org/cgit/aur.git/commit/?h=appimagelauncher-git&id=5c8844eeb18f1a4d86bf18270ee7546aec804bf6

Testing this on my system gives a conflict error with `vim` & `tinyxxd`.

```console
$ yay -Syu --sudoloop  

[...SNIP...]

   extra/tinyxxd            -> 1.3.7-1
   (make dependency of appimagelauncher-git)

[...SNIP...]

AUR Explicit (1): appimagelauncher-git-r1329.3d42d4c-2

[...SNIP...]

:: tinyxxd-1.3.7-1 and vim-9.1.1120-1 are in conflict (xxd). Remove vim? [y/N] y
error: failed to prepare transaction (could not satisfy dependencies)
:: removing vim breaks dependency 'vim' required by libguestfs
 -> error installing repo packages
error installing repo packages
```

You might want to change the make depends to use just `xxd`, since both `vim` and `tinyxxd` have: `Provides: xxd`

Should I open a separate issue for this?

**Comment by FabioLolix** [comment]
Synced on AUR https://aur.archlinux.org/cgit/aur.git/commit/?h=appimagelauncher-git&id=7827f848be30c9f66f9c1e8b9d656dc129ce78c5
