### ISSUE TITLE
appimagelauncherd causes system stutter every 30 seconds on Ubuntu 22.04 LTS with GNOME

### ISSUE THREAD

**Issue by fir3-1ce** [TheAssassin/AppImageLauncher#618]
### Pre-submit checks

- [X] I [checked for similar issues](https://github.com/TheAssassin/AppImageLauncher/issues?q=) beforehand, but could not find any, not even closed ones. I could not add my bug report to any existing issue.
- [X] I am going to take the time to to fill in all the required details. I know that the bug report will be dismissed otherwise.

### Describe the bug

It took me a long time to figure out what was causing this problem, but appimagelauncherd causes only certain icons to repaint in the dock every 30 seconds on the dot (pics below). This causes a slight lag/display stutter that varies in severity over time. It's worse on Wayland than it is on X. I wrote a full report on AskUbuntu when I was trying to diagnose the problem:

https://askubuntu.com/questions/1495200/icons-disappearing-reappearing-causing-input-lag/1495313#1495313

It happens with all Wine programs while appimagelauncherd is running, but I also saw it happen on some dpkgs, notably OpenSnitch.

I unchecked the setting to let appimagelauncherd run in the background, but still, every time I boot into my PC it would start by default, and I'd have to manually end the process in Task Manager. This was enough for me to uninstall the software altogether. Hopefully this gets fixed.

![example1](https://github.com/TheAssassin/AppImageLauncher/assets/113863279/d19f3bdc-8e10-44da-af77-06bcdf200304)

### Expected behavior

I expected the system stutter to not happen, but I also would have liked a way to see the daemon disabled completely, or only enabled when needed for certain processes before being disabled again.

### Steps to reproduce the issue

Boot into an Ubuntu 22.04 LTS live CD (standard version with GNOME)

Install some program with Wine, such as foobar2000

Install AppImageLauncher

Open foobar while appimagelauncherd is running, and watch the icons repaint every 30 seconds

### Screenshots

https://i.stack.imgur.com/9itlX.gif

https://i.stack.imgur.com/VKiLl.gif

https://i.stack.imgur.com/mKYJP.jpg

### Distribution and desktop environment

Ubuntu 22.04 LTS release
GNOME 42.9

### Installed AppImageLauncher version

Whatever the latest version at this ppa is, https://launchpad.net/~appimagelauncher-team/+archive/ubuntu/stable

I uninstalled a couple of weeks ago but it looks like the ppa hasn't been updated in a while.

appimagelauncher 202211022349-stable-0f91801~ubuntu22.04.1 

### List of AppImages you tried

not relevant

### Additional context

no other info needed

**Comment by artenax** [comment]
Judging by the log:
systemctl start --user appimagelauncherd
journalctl --user > log.txt
sudo fatrace

appimagelauncherd service checks for the /Applications folder every 30 seconds and if it is missing, it writes about it to the user log. I fixed it like this:

sudo mkdir /Applications
sudo chmod 777 /Applications

It's a folder in the root of the partition, besides ~/Applications

**Comment by mweidner037** [comment]
I am seeing the same behavior (certain icons repainting every 30 seconds). It stopped once I killed appimagelauncherd.

System: Ubuntu 22.04.3 LTS, Wayland, Gnome 42.9
appimagelauncher version: 202211022349-stable-0f91801~ubuntu22.04.1 (latest from `sudo add-apt-repository ppa:appimagelauncher-team/stable`)
Icons affected: Wine app; Electron.js app in dev mode.

There is also a second AskUbuntu thread about this behaviour & AppImageLauncher, which is what led me here: https://askubuntu.com/a/1319165

**Comment by OWL4C** [comment]
I reinstalled a clean Kubuntu 23.10 today, and had the same problems until restart, at which point it was #612 again. I uninstalled again (this time i was using the lite version) but even after a restart the problems persisted. I found no .config/Appimage* anything, and the .local folders looked clear too. I have a timeshift btrfs snapshot to compare against but the amount of data is huge.
Since the problems persisted a reboot after uninstalling it must have changed some file within these two folders since deleting them fixed it and no systemd service from appimagelauncher could have been running.

**Comment by OWL4C** [comment]
Okay i just retried with another clean install, same issue, after clicking any appimage the entire desktop will freeze, some things sometimes work and after a reboot Plasma doesn't start. Removing .local .config and .cache allowed it to work again. Since installing the .deb and rebooting wasn't causing the issue, but only activating any appimage and going through the setup (choosing a directory) i would think the 'deleting files fix' only removes some appimagelauncher config that basically resets it as if uninstalled. Mentioning #612 since this is the newer and more visible, but both are relevant.
Since there is no interaction or potential fix in sight i am now trying out alternatives like GearLever and appimaged.

**Comment by TheAssassin** [comment]
Have you tried the continuous release? The "stable" release has not seen many fixes and I'm still struggling with providing packages for the upcoming stable release; consider the continuous release a release candidate, the only thing that keeps me from releasing a new version is packaging.

**Comment by billbeans** [comment]
> Have you tried the continuous release? 

Where/how do I install the continuous release?

**Comment by billbeans** [comment]
@TheAssassin,
Did you mean the daily PPA? I have installed it on Ubuntu 22.04, but it hasn't been updated in over a year. Unfortunately the same problem persists - appimagelauncherd starts at login regardless of whether I had the box checked or not. I "fixed" this by adding `killall appimagelauncherd` to my `~/.profile`. The program probably shouldn't do this, but I still get to enjoy the benefits of AppImageLauncher without the system stutters now.

**Comment by TheAssassin** [comment]
No, I mean https://github.com/TheAssassin/AppImageLauncher/releases/continuous. Will be updated soon-ish.
